# Get file by ID
GET http://localhost:8080/api/v1/files/{{fileId}}

###

# Upload a file
POST http://localhost:8080/api/v1/files
Content-Type: multipart/form-data; boundary=--boundary

----boundary
Content-Disposition: form-data; name="ownerId"

{{ownerId}}
----boundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

asdasd
----boundary--

###

# Update a file
PUT http://localhost:8080/api/v1/files/{{fileId}}
Content-Type: multipart/form-data; boundary=--boundary

----boundary
Content-Disposition: form-data; name="userId"

{{userId}}
----boundary
Content-Disposition: form-data; name="updatedFile"; filename="updated_example.txt"
Content-Type: text/plain

asdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasd
----boundary--



###

# Delete a file
DELETE http://localhost:8080/api/v1/files/{{fileId}}

###

# Delete multiple files
DELETE http://localhost:8080/api/v1/files
Content-Type: application/json

[
    "cc9fdb69-70d5-4014-bb24-0f54e06bd520",
    "8a517d8b-ac1f-427e-90f3-368210a06826"
]

###

# Get all files by user
GET http://localhost:8080/api/v1/files/user/{{userId}}

###

# Get files not shared by user
GET http://localhost:8080/api/v1/files/user/{{userId}}/not-shared

###

# Download a file
GET http://localhost:8080/api/v1/files/download/{{fileId}}

###

# Get all files owned or shared with user
GET http://localhost:8080/api/v1/files/all/{{userId}}
