### Create a new Group
POST http://localhost:8080/api/v1/groups
Content-Type: application/json

{
  "name": "New TEST",
  "description": "This is a new group",
  "ownerId": "3ac41799-8593-423f-8166-b7af01685d5a"
}

> {%
    client.test("Create Group", function() {
        client.assert(response.status === 201, "Expected status 201, got " + response.status);
        client.assert(response.body.id !== undefined, "Response does not contain 'id'");
    });
%}

### Retrieve a Group by ID
GET http://localhost:8080/api/v1/groups/{{groupId}}

> {%
    client.test("Get Group by ID", function() {
        client.assert(response.status === 200, "Expected status 200, got " + response.status);
    });
%}

### Update a Group
PUT http://localhost:8080/api/v1/groups/{{groupId}}
Content-Type: application/json

{
  "id": "{{groupId}}",
  "name": "Updated TEST Name",
  "description": "Updated group description"
}

> {%
    client.test("Update Group", function() {
        client.assert(response.status === 200, "Expected status 200, got " + response.status);
        client.assert(response.body.name === "Updated Group Name", "Group name did not update");
    });
%}

### Delete a Group by ID
DELETE http://localhost:8080/api/v1/groups/{{groupId}}

> {%
    client.test("Delete Group by ID", function() {
        client.assert(response.status === 204, "Expected status 204, got " + response.status);
    });
%}

### Add Users to Group
PUT http://localhost:8080/api/v1/groups/{{groupId}}/add-users
Content-Type: application/json

[
  "ea7b9098-6fae-4fd0-83b5-60cbf7d3ca62",
  "927078b4-3a28-466f-9727-c29f0db78fac"
]

> {%
    client.test("Add Users to Group", function() {
        client.assert(response.status === 200, "Expected status 200, got " + response.status);
        client.assert(response.body.users.length >= 2, "Users were not added to the group");
    });
%}

### Remove Users from Group
PUT http://localhost:8080/api/v1/groups/{{groupId}}/remove-users?ownerId={{ownerId}}
Content-Type: application/json

[
  "927078b4-3a28-466f-9727-c29f0db78fac"
]


> {%
    client.test("Remove Users from Group", function() {
        client.assert(response.status === 200, "Expected status 200, got " + response.status);
    });
%}

### Get all Groups by User ID
GET http://localhost:8080/api/v1/groups/user/{{userId}}

> {%
    client.test("Get all Groups by User ID", function() {
        client.assert(response.status === 200, "Expected status 200, got " + response.status);
    });
%}

### Get all Groups
GET http://localhost:8080/api/v1/groups

> {%
    client.test("Get all Groups", function() {
        client.assert(response.status === 200, "Expected status 200, got " + response.status);
        client.assert(Array.isArray(response.body), "Response body is not an array");
    });
%}
